cab/urls.py
from django.views.generic import RedirectView
from django.conf.urls import url, include
from django.contrib import admin
from cab.views import *
from refferal import views


urlpatterns = [
    url(r'^bookcab/', bookcab, name='bookcab'),
    url(r'^app/bookcab/', bookcab_app, name='bookcab_app'),
    url(r'^booknow/', booknow, name='booknow'),
    url(r'^app/booknow/', booknow_app, name='booknow_app'),
    url(r'^postcab/', postcab, name = 'postcab'),
    url(r'^app/postcab/', postcab_app, name = 'postcab_app'),
    url(r'^$', index, name='index'),
    url(r'^hotels/', hotels, name='hotels'),
    url(r'^dashboard/', dashboard, name='dashboard'),
    # url(r'^earn_money/', earn_money, name='earn_money'),
    url(r'^buses/', bus, name='bus'),
    url(r'^flights/', flights, name='flights'),
    url(r'^blog/', blog, name='blog'),
    url(r'^about/', about, name='about'),
    url(r'^routes/', routes, name='routes'),
    url(r'^press_release/', press_release, name='press_release'),
    url(r'^faq/', faq, name='faq'),
    url(r'^career/', career, name='career'),
    url(r'^feedbacks/', feedback, name='feedback'),
    url(r'^privacy_policy/', privacy_policy, name='privacy_policy'),
    url(r'^terms_and_conditions/', terms_and_conditions, name='terms_and_conditions'),
    # url(r'^search/', search, name='search'),
    url(r'^summary/', summary, name='summary'),
    url(r'^cab/cities/', cab_cities, name='cab_cities'),
    url(r'^wallet/', views.wallet, name='wallet'),
    url(r'^forgot_password/', forgot_password, name='forgot_password'),
    url(r'^change_password/', change_password, name='change_password'),
    url(r'^edit_profile/', edit_profile, name='edit_profile'),
]

cabme/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cabme.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.urls', namespace='registration')),
    url(r'^', include('cab.urls', namespace='cab')),
    url(r'^vendor/', include('vendor.urls', namespace='vendor')),
    url(r'^refferal/', include('refferal.urls', namespace='refferal')),
     url(r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT, })
)

cab/models.py
from django.db import models
from django.contrib.auth.models import User
from registration.models import *
from b_cab.models import *


cities = (
	('test', 'test'),
	)
class BookCab(models.Model):

	From = models.ForeignKey('City', null = True, related_name = 'book_from')
	To = models.ForeignKey('City', null = True, related_name = 'book_to')
	Date = models.CharField(blank = False, null = False, max_length = 10)
	Date_return = models.CharField(blank = False, null = False, max_length = 10, default = '')
	Time = models.CharField(max_length = 10)
	Oneway = models.BooleanField(default = True)
	Price = models.IntegerField()
	Type = models.CharField(max_length=20)
	Sharing = models.BooleanField(default=False)
	Cust = models.ManyToManyField('registration.UserProfile', related_name = 'userprofile', null = True) 

	def __unicode__(self):
		return str(self.id)

class Cab(models.Model):
	From = models.ForeignKey('City', null = True, related_name = 'cab_from')
	To = models.ForeignKey('City', null = True, related_name = 'cab_to')
	DriverName = models.CharField(max_length = 100, blank = False, default = '')
	Date = models.CharField(null = True, max_length = 10,blank = True)
	Date_return = models.CharField(null = True, max_length = 10, default = '',blank = True)
	Time = models.CharField(max_length = 10,blank = True)
	Type = models.CharField(max_length=20)	
	cab_id = models.CharField(max_length = 1000, default = '')
	price = models.IntegerField(default = 7, blank = False)

	# def save(self, *args, **kwargs):
	# 	self.cab_id = str(self.id)
	# 	super(Cab, self).save(*args, **kwargs)
	
	def __unicode__(self):
		return str(self.cab_id)

class PostCab(models.Model):
	From = models.ForeignKey('City', null = True, related_name = 'post_from')
	To = models.ForeignKey('City', null = True, related_name = 'post_to')
	Date = models.CharField(blank = False, null = False, max_length = 10)
	Date_return = models.CharField(blank = False, null = False, max_length = 10, default = '')
	Time = models.CharField(max_length = 10)
	Type = models.CharField(max_length=20)	
	Smoking = models.BooleanField(default = False)
	Pet = models.BooleanField(default = False)
	Music = models.BooleanField(default = False)
	SeatsAvail = models.IntegerField(default = 2)
	user = models.ForeignKey(User, blank = False, default = '')
	price = models.IntegerField(default = 0, blank = False)
	cab_id = models.CharField(max_length = 1000, default = '') #when posting the cab save this object by appending a character 'p' in front of the auto id of this object

	def __unicode__(self):
		return str(self.id)	

class City(models.Model):
	name = models.CharField(max_length = 100, blank = False)
	suv_price = models.IntegerField(null = True)
	sedan_price = models.IntegerField(null = True)
	hatch_price = models.IntegerField(null = True)

	def __unicode__(self):
		return self.name

class InterCity(models.Model):
	From = models.ForeignKey('City', null = True, related_name = 'inter_from')
	To = models.ForeignKey('City', null = True, related_name = 'inter_to')
	Price = models.IntegerField(default= 7, null = True)
	Type = models.CharField(max_length = 50, null = True)
	cab_id = models.CharField(max_length = 50, null = True)

	def __unicode__(self):
		return self.From.name + self.To.name + self.Type

	def save(self, *args, **kwargs):
		self.cab_id = 'i' + str(self.id)
		super(InterCity, self).save(*args, **kwargs)

cab/views.py
from django.shortcuts import render
from .models import *
from registration.models import *
from django.http import HttpResponseRedirect,Http404,HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
import requests
from django.core.exceptions import ObjectDoesNotExist
from django.core.cache import cache
from django.contrib.auth import authenticate
import random
import string
import json
from urllib2 import urlopen
from vendor.models import Driver, Vendor
from vendor.models import Cab as vendor_cab
import uuid
import re


def index(request):
	if request.user.id == None:
		return render(request, 'cab/index.html')
		print request.user
	elif request.user.username == 'admin':
		context = {'name': 'admin'}
		return render(request, 'cab/index.html', context)
	else:
		user = request.user
		print user.username
		try:
			customer = UserProfile.objects.get(email_id = user.username)
			name = customer.name
		except ObjectDoesNotExist:
			name = ' '
		print name
		context = {'name': name, 'login': 1}
		return render(request, 'cab/index.html', context)

@login_required(login_url='/accounts/login/')
def dashboard(request):
	user_p = UserProfile.objects.get(user = request.user)
	name = user_p.name
	email = user_p.email_id
	contact = user_p.phone
	book_cab = []
	bookedcabs = user_p.bookedcabs.all()
	if len(bookedcabs) == 0:
		book_cab = 0
	else:
		for cab in bookedcabs:
			cab_type = cab.Type
			route = 'Oneway' if cab.Oneway == True else 'RoundTrip'
			From = cab.From
			To = cab.To
			Date = cab.Date
			Date_return = cab.Date_return
			distance_url = '''https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=%s&destinations=%s&key=AIzaSyDa8dUK8TSX2Iw-zI9YwLkm5VekKKmkyIQ''' %(From, To)
			distance_json = urlopen(distance_url)
			distance = int(json.load(distance_json)['rows'][0]['elements'][0]['distance']['text'][:-3]) #int(distance_json.split('],')[2].split(' : ')[4].split('"')[1][:-3]) #google api call
			fare = cab.Price*distance*1.609 #distance*cab.price
			time = cab.Time
			book_cab.append({'cab_type': cab_type, 'route': route, 'From': From, 'To': To, 'Date': Date, 'Date_return': Date_return, 'fare': fare,'time':time})
	
	context = {'name': name, 'email': email, 'contact': contact, 'book_cab': book_cab}

	return render(request, 'cab/dashboard.html', context)

# def earn_money(request):
# 	resp = {'refer_stage':UserProfile.objects.get(user=request.user).refer_stage, }
# 	return render(request, 'cab/earn_money.html',resp)

def hotels(request):
	return render(request, 'cab/hotels.html')

def flights(request):
	return render(request, 'cab/flights.html')

def bus(request):
	return render(request, 'cab/bus.html')


def search(request):
	return render(request, 'cab/search.html')

@login_required(login_url='/accounts/login/')
@csrf_exempt
def summary(request):
	print request.POST
	print request.session['uid']
	print cache.get(request.session['uid'])
	# user = UserProfile.objects.get(user = request.user)

	cab_id = request.POST['cab_id']
	cab_cache = cache.get(request.session['uid'])
	while cab_cache == None:
		cab_cache = cache.get(request.session['uid'])
	print cab_cache
	# print cab_cache['From']
	cab_from = cab_cache['From']
	cab_to = cab_cache['To']
	cab_date = cab_cache['Date']
	cab_date_return = cab_cache['Date_return']
	try:
		cab = Cab.objects.get(cab_id = cab_id)
		distance_url = '''https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=%s&destinations=%s&key=AIzaSyDa8dUK8TSX2Iw-zI9YwLkm5VekKKmkyIQ''' %(cab_from, cab_to)
		distance_json = urlopen(distance_url)
		distance = (int(json.load(distance_json)['rows'][0]['elements'][0]['distance']['text'][:-3]))*1.60934 #int(distance_json.split('],')[2].split(' : ')[4].split('"')[1][:-3]) #google api call
		price = cab.price*distance 
		print cab.price
	except ObjectDoesNotExist:
		cab = InterCity.objects.get(cab_id = cab_id)	
		price = cab.Price
	cab_type = cab.Type
	 #distance*cab.price
	service_tax = float(.06*price)
	total_price = price+service_tax
	resp = {'cab_id': cab_id, 'cab_type': cab_type, 'From': cab_from, 'To': cab_to, 'Date': cab_date, 'Date_return': cab_date_return, 'Distance': distance, 'Price': price, 'Service_Tax': service_tax, 'Total_Price': total_price,'Phone':UserProfile.objects.get(user=request.user).phone}
	return render(request, 'cab/summary.html', resp)

def blog(request):
	return render(request, 'cab/blog.html')

def about(request):
	return render(request, 'cab/about.html')

def faq(request):
	return render(request, 'cab/faq.html')


def career(request):
	return render(request, 'cab/career.html')



def privacy_policy(request):
	return render(request, 'cab/privacy_policy.html')


def press_release(request):
	return render(request, 'cab/press_release.html')

def terms_and_conditions(request):
	return render(request, 'cab/terms_and_conditions.html')

def routes(request):
	return render(request, 'cab/routes.html')

def cab_cities(request):
	cities = City.objects.all()
	c_name = []
	x = 0
	for city in cities:
		c_name.append(city.name)
		x+=1
	resp = {'cities': c_name}
	return JsonResponse(resp)

@csrf_exempt
def bookcab(request):
	if request.POST:
		cache.clear()
		tempuidlist = str(uuid.uuid1()).split('-')
		request.session['uid'] = str(('').join(tempuidlist))
		key = request.session['uid']
		b_cab = BookCab()
		try:
			From_tmp = City.objects.get(name = (request.POST['From']).lower())
		except ObjectDoesNotExist:
			print request.POST['From']
			City.objects.create(name = (request.POST['From']).lower(), suv_price = 12, sedan_price = 10, hatch_price = 8)
			From_tmp = City.objects.get(name = (request.POST['From']).lower())

		try:
			To_tmp = City.objects.get(name = (request.POST['To']).lower())
		except ObjectDoesNotExist:
			City.objects.create(name = (request.POST['To']).lower(), suv_price = 12, sedan_price = 10, hatch_price = 8)
			To_tmp = City.objects.get(name = (request.POST['To']).lower())

		print From_tmp
		print To_tmp
		b_cab.From = From_tmp
		b_cab.To = To_tmp
		b_cab.Date = request.POST['Date']
		b_cab.Date_return = request.POST['Date_return']

		distance_url = '''https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=%s&destinations=%s&key=AIzaSyDa8dUK8TSX2Iw-zI9YwLkm5VekKKmkyIQ''' %(b_cab.From, b_cab.To)
		distance_json = urlopen(distance_url)
		distance = int(json.load(distance_json)['rows'][0]['elements'][0]['distance']['text'][:-3]) 
		cust_cache = cache.set(key,
			{'From': b_cab.From,
			 'To': b_cab.To,
			 'Date': b_cab.Date,
			 'Date_return': b_cab.Date_return,
			 'OneWay': request.POST['OneWay'],
			 'distance': distance
			}
			)
		# b_cab.Time = request.POST['Time']
		if request.POST['OneWay'] == 'One Way':
			b_cab.OneWay = True
		else: 
			b_cab.OneWay = False

		if request.POST['Sharing'] == 'Sharing':
			b_cab.Sharing = True
		else: 
			b_cab.Sharing = False

		cabs_city = InterCity.objects.filter(From = b_cab.From, To = b_cab.To)
		if len(cabs_city) == 0:
			cabs = Cab.objects.filter(From = b_cab.From, To = b_cab.To, DriverName = 'Simha')
			if len(cabs) == 0:
			# except ObjectDoesNotExist:
				# try:
				Cab.objects.create(From = b_cab.From, To = b_cab.To, DriverName = 'Simha', Type = 'SUV', price = b_cab.From.suv_price)
				cab1 = Cab.objects.get(From = b_cab.From, To = b_cab.To, DriverName = 'Simha', Type = 'SUV', price = b_cab.From.suv_price)
				cab1.cab_id = str(cab1.id)
				cab1.save()
				Cab.objects.create(From = b_cab.From, To = b_cab.To, DriverName = 'Simha', Type = 'Sedan', price = b_cab.From.sedan_price)
				cab2 = Cab.objects.get(From = b_cab.From, To = b_cab.To, DriverName = 'Simha', Type = 'Sedan', price = b_cab.From.sedan_price)
				cab2.cab_id = str(cab2.id)
				cab2.save()
				Cab.objects.create(From = b_cab.From, To = b_cab.To, DriverName = 'Simha', Type = 'Hatchback', price = b_cab.From.hatch_price)
				cab3 = Cab.objects.get(From = b_cab.From, To = b_cab.To, DriverName = 'Simha', Type = 'Hatchback', price = b_cab.From.hatch_price)
				cab3.cab_id = str(cab3.id)
				cab3.save()
				# except:
				# 	Cab.objects.create(From = b_cab.From, To = b_cab.To, DriverName = 'Simha', Type = 'SUV', price = 12)
				# 	Cab.objects.create(From = b_cab.From, To = b_cab.To, DriverName = 'Simha', Type = 'Sedan', price = 10)
				# 	Cab.objects.create(From = b_cab.From, To = b_cab.To, DriverName = 'Simha', Type = 'Hatchback', price = 8)				
			else:
				pass
		else:
			pass
		try:
			cabs = Cab.objects.filter(From = b_cab.From, To = b_cab.To)	
			print cabs
		except ObjectDoesNotExist:
			pass

		try:
			p_cabs = PostCab.objects.filter(From = b_cab.From, To = b_cab.To, Date = b_cab.Date)
		except ObjectDoesNotExist:
			pass
		try:
			share_cabs = BookCab.objects.filter(From = b_cab.From, To = b_cab.To, Date = b_cab.Date, Sharing = True)	
		except ObjectDoesNotExist:
			pass
			
		D_name = []
		D_phone = []
		Price = []
		type_cab = []
		cab_id = []
		cust_names = []
		From = []
		To = []
		Date = []
		Date_return = []
		# Time = []
		OneWay = []
		Sharing = []

		if b_cab.OneWay == True and b_cab.Sharing == True:
			try:
				for cab in p_cabs:
					D_pcab = p_cabs.user
					D_pcabuserp = UserProfile.objects.get(user = D_pcab)
					D_name.append(D_pcabuserp.name)
					D_phone.append(D_pcabuserp.phone)
					Price.append(p_cabs.price*distance)
					# price_pcab = p_cabs.price
					# type_c = cab.Type 
					type_cab.append(p_cabs.type)
					cab_id.append(p_cab.cab_id) # not for display to users only for returning in the post request to backend
					# pcab_id = p_cabs.id # not for display to users only for returning in the post request to backend
					cust_names.append(D_pcabuserp.name)

cab/templates/cab/about.html
{% extends 'cab/base.html' %}


{% block content %}
  <div class="back-drop"> </div>
 <div class="row">
      <div class="blog-panel">
          <div class="card type-1">
          <div class="headers">
                    <ul>
                        <li class="active"><a href="{% url 'cab:about' %}">About Us</a></li> 
                    </ul>
                </div>
              <div class="row">
                <h3 class="card-label about-title">About CabMe</h3>
            </div>
            <div class="row blog-details">
                
                <div class="row about-content">
                    <div class="col-s1">
                        
                        <div class="text-content"><p>
                            CabMe is different from other cab services. We empower our customers by letting them choose from what we provide them best. You can customize your entire ride, even the road you want to travel on! Furthermore, CabMe brings you the innovative option of sharing the ride, where you can post about your travel plans and carpool with others to reduce individual travel costs.</p>

                            <p>Our objective is to make travelling an enjoyable and comfortable experience, and our priority is to make this experience safe and worthwhile.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
          <div class="card type-1">
        
              <div class="row">
                <h3 class="card-label about-title">
                            Who We Are</h3>
            </div>
            <div class="row blog-details">
                
                <div class="row about-content">
                    <div class="col-s1">
                        
                        <div class="text-content"><p>
                            We are a group of sapient BITSians who based CabMe on one simple idea – You’re the one who’s travelling, so you should get to choose how. Being students at the remote setting of Pilani, we know the set of troubles one faces when planning a journey. So our aim is to solve it for you!</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <div class="card type-1">
        
              <div class="row">
                <h3 class="card-label about-title">
                            What We Do</h3>
            </div>
            <div class="row blog-details">
                
                <div class="row about-content">
                    <div class="col-s1">
                        
                        <div class="text-content"><p>
                          
We at CabMe are working full time to make your journeys safe, comfortable, and perhaps most importantly, affordable. We aim to create a single platform for intercity cab journeys where you can book, share and create travel packages through a simple click on our website.</p>
                            <div class="row">
                                <div class="col-s2">
                                    <ul>
    <li>One way cabs</li>

    <li>Two way cabs</li>
    <li>Share your cabs
</li>
    <li>Get the shared cab
</li>
                                    </ul>
                                </div>
                                <div class="col-s2">
                                    <ul>
                                        <li>Pilani</li>
    <li>Kanpur</li>
    <li>Kharagpur</li>
    <li>Bangalore</li>
    


                                    </ul>
                                </div>
                            

    



                            </div>
                                
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="blog-featured">
      <div class="card type-1">
          <div class="row">
            <h3 class="card-label">Quick Links <span>&gt;</span></h3>
        </div>
        <div class="row">
        <div class="col-s1 featured-list">
          <ul>
              <li><a href="{% url 'cab:blog' %}">Blog</a></li>
              <li><a href="{% url 'cab:career' %}">Careers</a></li>
              <li><a href="{% url 'cab:faq' %}">FAQ</a></li>
              <li><a href="{% url 'cab:privacy_policy' %}">Privacy Policy</a></li>
              <li><a href="{% url 'cab:terms_and_conditions' %}">Terms And Conditions</a></li>
              <li><a href="{% url 'cab:index' %}">Feedback</a></li>
              <li><a href="{% url 'cab:press_release' %}">Press Release</a></li>
              <li><a href="{% url 'cab:index' %}">Testimonials</a></li>
          </ul>
        </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

cab/templates/cab/career.html
{% extends 'cab/base.html' %}
{% block content %}
  <div class="back-drop"> </div>
 <div class="row">
      <div class="career-panel">
          <div class="col-s3">
          <div class="card type-1">
          <div class="headers">
                    <ul>
                        <li class="active"><a href="{% url 'cab:index' %}">Career</a></li> 
                    </ul>
                </div>
              <div class="row">
        
            </div>
            <div class="row career-details">
                
                <div class="row press-content">
                  
                        <div class="col-s1">
                        <div class="text-content career-text"><h3>Internship</h3>
                            <p>
                           We are providing Internship to students who are dedicated and want to get a on ground experience. We are looking for no excellent resume but for dedication which they can show towards the company.
</p>
                        </div>
                    </div>
                </div>
                   <div class="career-apply">
                    <h3 id="internship-apply">APPLY</h3>
                </div>
                     
                 
              
            </div>
        </div>
      
    </div>
           <div class="col-s3">
          <div class="card type-1">
        
              <div class="row">
        
            </div>
            <div class="row career-details">
                
              
                    <div class="row press-content">
                  
                        <div class="col-s1">
                        <div class="text-content career-text"><h3>Content Writers</h3>
                        
                            <p>Job Responsibilities:<br>

We want people who want to show their talent in writing blogs and We are open for inexperienced but who are willing to dedicate 1-2 hours everyday on creating blogs for CabMe. </p>
                        </div>
                    </div>
                </div>
                     
                  <div class="career-apply">
                    <h3 id="content-writer-apply">APPLY</h3>
                </div>
              
            </div>
        </div>
      
    </div>
           <div class="col-s3">
          <div class="card type-1">
         
              <div class="row">
        
            </div>
            <div class="row career-details">
                
              
                      <div class="row press-content">
                  
                        <div class="col-s1">
                        <div class="text-content career-text"><h3>Video Making</h3>
                     
                            <p>Job Responsibilities:<br>

Good video makers with enough knowledge of graphic designing and video editing are required.

We would basically want enough hardwork and dedication from those who apply.</p>

                        </div>
                    </div>
                </div>
                 
                 <div class="career-apply">
                    <h3 id="video-apply">APPLY</h3>
                </div>
                 
              
            </div>
        </div>
      
    </div>
    </div>
          
    <div class="blog-featured">
      <div class="card type-1">
          <div class="row">
            <h3 class="card-label">Quick Links <span>&gt;</span></h3>
        </div>
        <div class="row">
        <div class="col-s1 featured-list">
          <ul>
              <li><a href="{% url 'cab:about' %}">About</a></li>
              <li><a href="{% url 'cab:blog' %}">Blog</a></li>
              <li><a href="{% url 'cab:faq' %}">FAQ</a></li>
              <li><a href="{% url 'cab:privacy_policy' %}">Privacy Policy</a></li>
              <li><a href="{% url 'cab:terms_and_conditions' %}">Terms And Conditions</a></li>
              <li><a href="{% url 'cab:index' %}">Feedback</a></li>
              <li><a href="{% url 'cab:press_release' %}">Press Release</a></li>
              <li><a href="{% url 'cab:index' %}">Testimonials</a></li>
          </ul>
        </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

cab/templates/cab/faq.html
{% extends 'cab/base.html' %}
{% block content %}

  <div class="back-drop"> </div>
 <div class="row">
      <div class="blog-panel">
          <div class="card type-1">
          <div class="headers">
                    <ul>
                        <li class="active"><a href="{% url 'cab:index' %}">FAQ</a></li> 
                    </ul>
                </div>
              <div class="row">
        
            </div>
            <div class="row blog-details">
                
                <div class="row press-content">
                  
                        <div class="col-s1">
                        <div class="text-content faq-text"><h3>General</h3>
                        <h2>What is CabMe.in?</h2>    
                            <p>
                           CabMe.in is an intercity cab service provider. We provide you a wide range of cars for selection (Sedan, SUV, hatchback, Luxury) to suit your needs. So if you want car for Outstation / CabSharing /Cab-Booking, One Way Drop, just visit CabMe.in and book it in 3 simple steps. </p>
                            <h2>
                             Cities -where we operate?</h2><p>
                           
We are currently offering our services in Pilani, Kanpur, Bangalore, Kharagpur, Bhubaneshwar. We provide Inter-city Car service to corporate in these cities.
</p>
                        </div>
                    </div>
                </div>
                    <div class="row press-content">
                  
                        <div class="col-s1">
                        <div class="text-content faq-text"><h3>Booking Related</h3>
                        
<h2>How do I book on CabMe.in?</h2>
                            <p>You can either book online through our website www.cabme.in or may call at +91 8890605392.</p>
<h2>How do I cancel my booking?</h2>
                           <p> You can call us at +91 8890605392. Please read our terms and conditions for clarity on the same.</p>
                        </div>
                    </div>
                </div>
                      <div class="row press-content">
                  
                        <div class="col-s1">
                        <div class="text-content faq-text"><h3>Pricing Related</h3>
                       <h2>How is the total fare/price calculated for an Outstation / Multi-city return trip (Inter-city) cab service?</h2>
                            <p>Intercity car fares constitute of various components as below:
                            <ol><li>Per KM Rate: This is base rate which will be charged on every km travelled. The rate varies with car model and city.</li>
                                <li> Minimum KM charged per day: We charge minimum distance of 250 kms per day for each city. Example for clarity: If you are using the vehicle for 4 days the minimum we will charge you is 4*250=1000 km, in case your actual usage for the three days (combined) is less (say 800 km) we will still charge you for 1000 km and in case your usage is higher (say 1150), we will charge you for your actual km used.</li>
                                <li>Daily Driver allowances: For intercity travel customers, you need to pay driver allowance. The allowance amount might vary cab or city wise but ranges from Rs 200 to 500. Apart from it night allowance also charged if driver runs the vehicle during night hours (10pm to 5am).</li>
                                <li>Toll, parking and state taxes: These will be charged on actual basis during/at end of the journey. You may askdriverto provide the relevant receipts if possible</li>
                                <li>Definition of a day: Day is defined as calendar day i.e. 12 midnight to next day 12 midnight for all the calculation purposes.</li>
                                <li> Service Tax: We charge service tax as per Govt rules, its 5.6% of total trip cost now-a-days.</li></ol></p>
                           <h2> How is the total fare/price calculated for a One Way Drop?</h2>
<p>For One Way Drop, we charge fixed cost for the trip as mentioned on our website exclusive of state, toll and service tax.</p>

                        </div>
                    </div>
                </div>
                      <div class="row press-content">
                  
                        <div class="col-s1">
                        <div class="text-content faq-text"><h3>Registration Related</h3>
                       
                            <h2>Do I need to register to avail the service?</h2>
                            <p>Yes you are required to register yourself for booking a cab because we need your contact number, pick up address and other basic details to serve you better .</p>

                        </div>
                    </div>
                </div>
                      <div class="row press-content">
                  
                        <div class="col-s1">
                        <div class="text-content faq-text"><h3> Payments Related</h3>
                      
                            <h2>How do I pay for the service ?</h2>
                            <p>We are taking cash as of now. You need to pay full amount to the driver.</p>
                        </div>
                    </div>
                </div>
              
            </div>
        </div>
      
    </div>
    <div class="blog-featured">
      <div class="card type-1">
          <div class="row">
            <h3 class="card-label">Quick Links <span>&gt;</span></h3>
        </div>
        <div class="row">
        <div class="col-s1 featured-list">
          <ul>
             <li><a href="{% url 'cab:about' %}">About</a></li>
              <li><a href="{% url 'cab:career' %}">Career</a></li>
              <li><a href="{% url 'cab:blog' %}">Blog</a></li>
              <li><a href="{% url 'cab:privacy_policy' %}">Privacy Policy</a></li>
              <li><a href="{% url 'cab:terms_and_conditions' %}">Terms And Conditions</a></li>
              <li><a href="{% url 'cab:index' %}">Feedback</a></li>
              <li><a href="{% url 'cab:press_release' %}">Press Release</a></li>
              <li><a href="{% url 'cab:index' %}">Testimonials</a></li>
              
          </ul>
        </div>
        </div>
    </div>
</div>
</div>
{% endblock %}